name: Frontend Continuous Integration
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checking Out the code from Repo
        uses: actions/checkout@v2

      - name: Setting up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache before dependency install
        id: CachingData
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
        
      - name: Installing dependencies
        run: npm ci

      - name: Now Running Lint
        run: npm run lint

  test:
    name: Testing
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checking Out the code from Repo
        uses: actions/checkout@v2

      - name: Setting up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache action to restore cache before dependency install
        id: CachingData
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
        
      - name: Installing dependencies
        run: npm ci

      - name: Now Running Tests
        run: npm run test

  build:
    name: Check out the code and build the Image
    runs-on: ubuntu-latest
    needs: [lint,test]
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Build the docker image
        run: docker build .
